### PR TITLE
Scott

### PR DESCRIPTION
**Pull request by swdunningASU**
Simple pull request.  Fixed User Story #77.  Bug fix in the new dialog box when clicking “x” for the dialog box itself caused Memoranda window to close instead of closing dialog box and canceling the action.  

Made one change/commit (added a check/conditional) in fileDoExit() method in AppFrame.

### CODE REVIEW

**Comment by abahrema** [comment]
I would like to approve this but need one more person to confirm.

**Comment by blparri1** [comment]
After selecting his branch and syncing, I am still having the issue.  Need someone else to check.

-Not approved for now

**Comment by blparri1** [comment]
If the X is selected on the frame, then the X in the dialog box, the entire program will close.  But if you select file->close, and then the X in the dialog box, it will cancel the close.  Not sure if this is intended.  My thoughts are that the X should always cancel.

**Comment by swdunningASU** [comment]
If it works for one it should work for the other because they both use the same method.  Make sure if you have any open classes before/after you switch branches you close them out before you refresh and run memoranda or it won't switch branches I've found.

**Pull request closed without merging**
